# Generated by Django 4.2.5 on 2023-10-04 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('scenic', models.CharField(max_length=20)),
                ('time', models.CharField(max_length=200)),
                ('cost', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ticket_fare',
            fields=[
                ('scenic', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('adult', models.IntegerField()),
                ('student', models.IntegerField()),
                ('kid', models.IntegerField()),
            ],
        ),
    ]
