# Generated by Django 4.2.5 on 2023-10-09 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_tickets'),
    ]

    operations = [
        migrations.CreateModel(
            name='ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField()),
                ('ticket_type', models.CharField(max_length=10)),
                ('ticket_cost', models.IntegerField()),
                ('identify', models.CharField(max_length=30)),
                ('travel_date', models.CharField(max_length=30)),
            ],
        ),
    ]
