# Generated by Django 4.2.5 on 2023-09-24 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.CharField(max_length=200)),
                ('salesman', models.CharField(max_length=200)),
                ('customer', models.CharField(max_length=200)),
            ],
        ),
    ]
